from __future__ import annotations

import json
from pathlib import Path


def get_run_model_path(run_id: str, *, dashboard_db_path: str | Path) -> str | None:
    """
    Resolve the pickled model path for a given MLflow `run_id` from the dashboard DB.

    The DB is generated by `scripts/build_dashboard_db.py` and stores raw MLflow params
    under `models[].params`.
    """
    run_id = str(run_id or "")
    if not run_id:
        return None

    db_path = Path(dashboard_db_path)
    if not db_path.exists():
        return None

    try:
        data = json.loads(db_path.read_text(encoding="utf-8"))
    except Exception:
        return None

    models = data.get("models", [])
    if not isinstance(models, list):
        return None

    for m in models:
        if not isinstance(m, dict):
            continue
        if str(m.get("id")) != run_id and str(m.get("run_id")) != run_id:
            continue
        params = m.get("params", {}) or {}
        if not isinstance(params, dict):
            return None
        model_path = params.get("model_path") or params.get("source_model_path")
        if not model_path:
            # Fallback if the path wasn't stored in params but it's a known model pattern
            if str(m.get("id")).startswith(f"{m.get('market')}_model"):
                model_path = f"models/{m.get('id')}.pkl"
            else:
                return None
        return str(model_path)

    return None


def get_run_profile_path(run_id: str, *, dashboard_db_path: str | Path) -> str | None:
    """
    Resolve the strategy profile path recorded in MLflow params for a given run.

    This is used to re-run backtests with the same profile (if the run logged it).
    """
    run_id = str(run_id or "")
    if not run_id:
        return None

    db_path = Path(dashboard_db_path)
    if not db_path.exists():
        return None

    try:
        data = json.loads(db_path.read_text(encoding="utf-8"))
    except Exception:
        return None

    models = data.get("models", [])
    if not isinstance(models, list):
        return None

    for m in models:
        if not isinstance(m, dict):
            continue
        if str(m.get("id")) != run_id and str(m.get("run_id")) != run_id:
            continue
        params = m.get("params", {}) or {}
        if not isinstance(params, dict):
            return None
        profile = params.get("profile")
        if not profile:
            return None
        return str(profile)

    return None
