"""Generate local schedules for Alpha Engine research automation."""

from __future__ import annotations

import platform
import shlex
import sys
from pathlib import Path

DAILY_LOCAL_CRON = "30 7 * * 2-6"


def _project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _quoted(path: Path) -> str:
    return shlex.quote(str(path))


def setup_posix_cron() -> str:
    """Write an importable crontab fragment for standalone research jobs."""

    project_root = _project_root()
    python_exe = Path(sys.executable).resolve()
    log_dir = project_root / "artifacts" / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)

    prefix = f"cd {_quoted(project_root)} &&"
    entries = [
        (
            DAILY_LOCAL_CRON,
            f"{prefix} {_quoted(python_exe)} scripts/run_latest_us_low_turnover_decision.py "
            f">> {_quoted(log_dir / 'daily_us_decision.log')} 2>&1",
        ),
        (
            "0 9 * * 1",
            f"{prefix} {_quoted(python_exe)} scripts/weekly_research.py --market us "
            f">> {_quoted(log_dir / 'weekly_research.log')} 2>&1",
        ),
        (
            "0 8 * * 1",
            f"{prefix} {_quoted(python_exe)} scripts/check_factor_decay.py --update-metadata "
            f">> {_quoted(log_dir / 'factor_decay.log')} 2>&1",
        ),
        (
            "0 10 * * 1",
            f"{prefix} {_quoted(python_exe)} scripts/generate_weekly_report.py "
            f">> {_quoted(log_dir / 'weekly_report.log')} 2>&1",
        ),
    ]

    cron_path = project_root / "artifacts" / "alpha-engine.crontab"
    lines = [
        "# Generated by scripts/setup_cron.py",
        "# SEC_USER_AGENT must be available to the cron environment.",
        *(f"{schedule} {command}" for schedule, command in entries),
        "",
    ]
    cron_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Crontab fragment written to {cron_path}")
    print(f"Review, then install with: crontab {_quoted(cron_path)}")
    print("Verify with: crontab -l")
    return str(cron_path)


def _windows_daily_batch(project_root: Path, python_exe: Path) -> str:
    return f"""@echo off
cd /d "{project_root}"
if not defined SEC_USER_AGENT (
  echo SEC_USER_AGENT is required for SEC Company Facts access.
  exit /b 2
)
if not exist artifacts\logs mkdir artifacts\logs
"{python_exe}" scripts\run_latest_us_low_turnover_decision.py >> artifacts\logs\daily_us_decision.log 2>&1
exit /b %ERRORLEVEL%
"""


def setup_windows_task() -> str:
    """Write Windows launchers and print Task Scheduler commands."""

    project_root = _project_root()
    python_exe = Path(sys.executable).resolve()
    weekly_batch = f"""@echo off
cd /d "{project_root}"
"{python_exe}" scripts\weekly_research.py --market us
"{python_exe}" scripts\check_factor_decay.py --update-metadata
"{python_exe}" scripts\generate_weekly_report.py
"""
    weekly_path = project_root / "scripts" / "run_weekly.bat"
    weekly_path.write_text(weekly_batch, encoding="utf-8")
    daily_path = project_root / "scripts" / "run_daily_us_decision.bat"
    daily_path.write_text(_windows_daily_batch(project_root, python_exe), encoding="utf-8")

    print(f"Weekly batch written to {weekly_path}")
    print(f"Daily decision batch written to {daily_path}")
    print("Set SEC_USER_AGENT as a persistent user environment variable first.")
    print(
        "Daily schedule: schtasks /create /f /tn \"AlphaEngine Daily US Decision\" "
        f"/tr \"{daily_path}\" /sc weekly /d TUE,WED,THU,FRI,SAT /st 07:30"
    )
    print(
        "Weekly schedule: schtasks /create /f /tn \"AlphaEngine Weekly Research\" "
        f"/tr \"{weekly_path}\" /sc weekly /d MON /st 09:00"
    )
    return str(daily_path)


def main() -> int:
    if platform.system() == "Windows":
        path = setup_windows_task()
        print(f"\nWindows automation setup complete: {path}")
    else:
        path = setup_posix_cron()
        print(f"\nPOSIX cron setup complete: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
