import pandas as pd
from tabulate import tabulate


def render_trade_ticket(date: str, candidates: pd.DataFrame, market: str) -> str:
    """
    Render a markdown trade ticket.
    candidates columns expected: 
    [symbol, score, close, ma20, vol_ratio, liquidity, guardrail_passed, reason]
    """
    
    # Filter for passed/failed
    buys = candidates[candidates['guardrail_passed'] == True].copy()
    rejects = candidates[candidates['guardrail_passed'] == False].copy()
    
    # Sort by score descending
    buys = buys.sort_values('score', ascending=False)
    
    md = f"# 🎫 Trade Ticket: {market.upper()} - {date}\n\n"
    
    md += "## ✅ Buy Recommendations\n"
    if buys.empty:
        md += "_No candidates passed guardrails today._\n"
    else:
        # Format table
        display_cols = ['symbol', 'score', 'close', 'ma20']
        md += tabulate(buys[display_cols].head(10), headers="keys", tablefmt="github", showindex=False)
        md += f"\n\n*Total Approved Candidates: {len(buys)}*\n"
        
    md += "\n## 🛑 Blocked/Rejected (Guardrails)\n"
    if rejects.empty:
        md += "_No candidates rejected._\n"
    else:
        display_cols_rej = ['symbol', 'score', 'reason']
        md += tabulate(rejects[display_cols_rej].head(10), headers="keys", tablefmt="github", showindex=False)
        
    md += "\n---\n*Generated by AI Trading Assistant*"
    return md
